version: '3'
services:
  api-user-crud:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: user-crud
    container_name: user-crud
    entrypoint: npm run start:dev
    env_file:
      ./.env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - './:/usr/src/app'
    ports:
      - '3000:3000'
    networks:
      - user-crud-network

networks:
  user-crud-network:
    name: user-crud-network
    driver: bridge